M48
; DRILL file {KiCad (6.0.0)} date Wed Feb 23 23:53:06 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-02-23T23:53:06-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
%
G90
G05
T1
X144.272Y-141.224
X169.418Y-187.198
X169.672Y-141.224
X169.672Y-160.782
T0
M30
